language: java
sudo: false
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2

install: true
script:
  - ./mvnw clean install
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
